name: Auto Generate Documentation

on:
  push:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Получить код
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    # Шаг 2: Установить Doxygen
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        doxygen --version
        
    # Шаг 3: Сгенерировать документацию
    - name: Generate documentation
      run: |
        echo "Generating Doxygen documentation..."
        doxygen Doxyfile  
        
    # Шаг 4: Закоммитить изменения обратно в репозиторий
    - name: Commit and push documentation
      run: |
        git config --local user.email "fischer.sascha333@gmail.com"
        git config --local user.name "SaNaFiS"
        git add ./html ./latex
        git commit -m "docs: auto-generate documentation"
        git push
